<?xml version="1.0" encoding="utf-8"?><Database Name="bdForo" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THEARKONE\SQLEXPRESS;Initial Catalog=bdForo;Integrated Security=True;Encrypt=False" SettingsObjectName="BackEnd2.Properties.Settings" SettingsPropertyName="bdForoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_INGRESAR_PUBLICACION" Method="SP_INGRESAR_PUBLICACION">
    <Parameter Name="ID_TEMA" Parameter="iD_TEMA" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="TITULO" Parameter="tITULO" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="MENSAJE" Parameter="mENSAJE" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>